name: nextcloud
version: 3.0.1
description: A Nextcloud client for dart which can use several official Nextcloud APIs
homepage: https://github.com/jld3103/dart-nextcloud

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ">=0.13.0 <0.14.0"
  intl: ">=0.17.0 <0.18.0"
  xml: ">=5.0.0 <6.0.0"

dev_dependencies:
  mockito: ">=5.0.0 <6.0.0"
  test: ">=1.17.0 <1.18.0"
